"""Centralized configuration for ATS Resume Optimizer."""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ATSConfig:
    keyword_min_length: int = 2
    max_keywords: int = 60
    max_injected_keywords: int = 15
    keyword_density_target: float = 0.03
    density_score_warning_threshold: float = 0.7
    formatting_min_word_count: int = 150
    section_heading_min_length: int = 3
    section_heading_max_length: int = 40
    required_sections: tuple[str, ...] = ("skills", "experience", "education")
    section_aliases: dict[str, tuple[str, ...]] = field(
        default_factory=lambda: {
            "skills": ("skills", "technical skills", "core skills", "competencies"),
            "experience": (
                "experience",
                "work experience",
                "professional experience",
                "employment",
            ),
            "education": ("education", "academic background", "academics"),
            "projects": ("projects", "project experience"),
            "certifications": ("certifications", "licenses", "certificates"),
            "summary": ("summary", "professional summary", "profile"),
        }
    )
    stopwords: frozenset[str] = frozenset(
        {
            "a",
            "about",
            "above",
            "after",
            "again",
            "against",
            "all",
            "am",
            "an",
            "and",
            "any",
            "are",
            "as",
            "at",
            "be",
            "because",
            "been",
            "before",
            "being",
            "below",
            "between",
            "both",
            "but",
            "by",
            "can",
            "could",
            "did",
            "do",
            "does",
            "doing",
            "down",
            "during",
            "each",
            "few",
            "for",
            "from",
            "further",
            "had",
            "has",
            "have",
            "having",
            "he",
            "her",
            "here",
            "hers",
            "herself",
            "him",
            "himself",
            "his",
            "how",
            "i",
            "if",
            "in",
            "into",
            "is",
            "it",
            "its",
            "itself",
            "just",
            "me",
            "more",
            "most",
            "my",
            "myself",
            "no",
            "nor",
            "not",
            "now",
            "of",
            "off",
            "on",
            "once",
            "only",
            "or",
            "other",
            "our",
            "ours",
            "ourselves",
            "out",
            "over",
            "own",
            "same",
            "she",
            "should",
            "so",
            "some",
            "such",
            "than",
            "that",
            "the",
            "their",
            "theirs",
            "them",
            "themselves",
            "then",
            "there",
            "these",
            "they",
            "this",
            "those",
            "through",
            "to",
            "too",
            "under",
            "until",
            "up",
            "very",
            "was",
            "we",
            "were",
            "what",
            "when",
            "where",
            "which",
            "while",
            "who",
            "whom",
            "why",
            "with",
            "would",
            "you",
            "your",
            "yours",
            "yourself",
            "yourselves",
        }
    )
    bullet_prefixes: tuple[str, ...] = ("-", "*", "•", "–", "—")
    ats_score_weights: dict[str, float] = field(
        default_factory=lambda: {
            "keyword_match": 0.50,
            "sections": 0.20,
            "density": 0.15,
            "formatting": 0.15,
        }
    )


DEFAULT_CONFIG = ATSConfig()
